### ISSUE TITLE
Folds all regions when file is opened

### ISSUE THREAD

**Issue by lrvpxl** [pierreglaser/folding-nvim#2]
Does the package immediately folds all regions when the file is opened? Because this is happening on my machine. If this is an intentional behaviour, can it be disabled? I'm using this package for Typescript files.

**Comment by zlksnk** [comment]
I found this happening because of another plugin installed. Closing the issue.

**Comment by zlksnk** [comment]
> I found this happening because of another plugin installed. Closing the issue.

My mistake! Issue is persisting even after removal of that plugin.

**Comment by lrvpxl** [comment]
🤦‍♂️ [Vim folds everything by default](https://vim.fandom.com/wiki/All_folds_open_when_opening_a_file) and that was causing the issue.
