### ISSUE TITLE
Fold on opening/writing buffer

### ISSUE THREAD

**Issue by manyids2** [pierreglaser/folding-nvim#4]
Hello, is it possible to disable folding when opening/writing a buffer? Right now it is being done automatically. I tried ( in the lua/folding.lua file ) commenting out the M.update_folds() method after M.setup_plugin(), but then it never finds any fold afterwards.

**Comment by pierreglaser** [comment]
Hi. I cannot reproduce the reported behavior on a `python` file. Have you set the `foldlevel` and `foldlevelstart` options? You can look the last time these options were set by typing `:verbose set foldlevelstart`.

**Comment by pierreglaser** [comment]
Closing since inactive.
