### ISSUE TITLE
New LSP request callback signature incompatible

### ISSUE THREAD

**Issue by Nicholas-Hein** [pierreglaser/folding-nvim#5]
Hello!

I noticed this plugin stopped working for me a little while ago, and, after a bit of debugging, I noticed that the LSP request callback handler `M.fold_handler()` has a method signature that is different than the signature specified in the documentation:

**folding-nvim:**

```lua
  function M.fold_handler(_, _, result, _, bufnr)
```

**`:h lsp-handler`:**

```lua
  function(err, result, ctx, config)
```

I've seen some of the newest NeoVim updates breaking a lot of LSP plugins lately, and, when I checked, that's what I think happened.  The issue seems to come from `bufnr` being `nil`.  Supposedly, `ctx['bufnr']` is where the new buffer number value should come from.  So I changed that and moved the `result` parameter to match the doc.

So, all in all, what made it work for me was doing this:
```lua
  function M.fold_handler(_, result, ctx, _)
      local bufnr = ctx['bufnr']
  ...
```

I am by no means an expert when it comes to this stuff, but I hope this helps!

**Comment by Open-Ocean-Software** [comment]
Also just found out that `result` in the LSP handler can be `nil`, so I changed the `if` guard to account for it.  i.e.:

```lua
if current_bufnr == bufnr then
```

becomes


```lua
if current_bufnr == bufnr and result ~= nil then
```

**Comment by pierreglaser** [comment]
Closing (see discussion in #6).
